# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 329)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lang_from = QtWidgets.QComboBox(self.centralwidget)
        self.lang_from.setObjectName("lang_from")
        self.horizontalLayout.addWidget(self.lang_from)
        self.change_lang = QtWidgets.QPushButton(self.centralwidget)
        self.change_lang.setMaximumSize(QtCore.QSize(50, 16777215))
        self.change_lang.setObjectName("change_lang")
        self.horizontalLayout.addWidget(self.change_lang)
        self.lang_to = QtWidgets.QComboBox(self.centralwidget)
        self.lang_to.setObjectName("lang_to")
        self.horizontalLayout.addWidget(self.lang_to)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_from = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_from.setObjectName("text_from")
        self.horizontalLayout_2.addWidget(self.text_from)
        self.text_to = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_to.setObjectName("text_to")
        self.horizontalLayout_2.addWidget(self.text_to)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Переводчик"))
        self.change_lang.setText(_translate("MainWindow", "<=>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
